//! Path builder for CPCV backtest paths.
//!
//! Given the CPCV splits, constructs complete backtest paths by stitching
//! together test-set segments from different splits so that every time-group
//! is covered exactly once in each path.

use super::combinatorial::CpcvSplit;

/// Build backtest paths from CPCV splits.
///
/// A backtest path is a sequence of split indices such that the union of their
/// test groups covers all `n_groups` groups exactly once. This function
/// uses a greedy/backtracking approach to find valid paths.
///
/// # Arguments
/// * `splits` - The CPCV splits generated by `CpcvConfig::generate_splits`.
/// * `n_groups` - Total number of groups (N).
///
/// # Returns
/// A vector of paths, where each path is a vector of split indices.
pub fn build_paths(splits: &[CpcvSplit], n_groups: usize) -> Vec<Vec<usize>> {
    if splits.is_empty() || n_groups == 0 {
        return Vec::new();
    }

    // Determine k from the first split
    let k = splits[0].test_groups.len();
    if k == 0 || n_groups % k != 0 {
        return Vec::new();
    }

    let splits_per_path = n_groups / k;
    let mut paths: Vec<Vec<usize>> = Vec::new();
    let mut current_path: Vec<usize> = Vec::new();
    let mut covered: Vec<bool> = vec![false; n_groups];

    build_paths_recursive(
        splits,
        n_groups,
        splits_per_path,
        &mut current_path,
        &mut covered,
        &mut paths,
        0,
    );

    paths
}

/// Check whether a split's test groups can be added without overlap.
fn can_use_split(split: &CpcvSplit, covered: &[bool], n_groups: usize) -> bool {
    split
        .test_groups
        .iter()
        .all(|&g| g < n_groups && !covered[g])
}

/// Mark or unmark test groups in the covered array.
fn set_covered(split: &CpcvSplit, covered: &mut [bool], value: bool) {
    for &g in &split.test_groups {
        covered[g] = value;
    }
}

/// Check whether we have a complete valid path.
fn is_complete_path(
    current_path: &[usize],
    splits_per_path: usize,
    covered: &[bool],
) -> Option<bool> {
    if current_path.len() == splits_per_path {
        Some(covered.iter().all(|&c| c))
    } else {
        None
    }
}

fn build_paths_recursive(
    splits: &[CpcvSplit],
    n_groups: usize,
    splits_per_path: usize,
    current_path: &mut Vec<usize>,
    covered: &mut Vec<bool>,
    paths: &mut Vec<Vec<usize>>,
    start_from: usize,
) {
    if let Some(complete) = is_complete_path(current_path, splits_per_path, covered) {
        if complete {
            paths.push(current_path.clone());
        }
        return;
    }

    if paths.len() >= 10000 {
        return;
    }

    for i in start_from..splits.len() {
        if !can_use_split(&splits[i], covered, n_groups) {
            continue;
        }

        set_covered(&splits[i], covered, true);
        current_path.push(i);
        build_paths_recursive(
            splits,
            n_groups,
            splits_per_path,
            current_path,
            covered,
            paths,
            i + 1,
        );
        current_path.pop();
        set_covered(&splits[i], covered, false);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cpcv::combinatorial::CpcvConfig;

    #[test]
    fn test_build_paths_basic() {
        let config = CpcvConfig {
            n_groups: 4,
            n_test_groups: 2,
        };
        let splits = config.generate_splits();
        let paths = build_paths(&splits, 4);

        // Each path should cover all 4 groups
        for path in &paths {
            let mut covered = [false; 4];
            for &split_idx in path {
                for &g in &splits[split_idx].test_groups {
                    assert!(!covered[g], "group {} covered twice", g);
                    covered[g] = true;
                }
            }
            assert!(covered.iter().all(|&c| c), "not all groups covered");
        }
    }

    #[test]
    fn test_build_paths_k1() {
        // k=1 means standard fold -- only one path: all splits
        let config = CpcvConfig {
            n_groups: 3,
            n_test_groups: 1,
        };
        let splits = config.generate_splits();
        let paths = build_paths(&splits, 3);
        assert_eq!(paths.len(), 1);
        assert_eq!(paths[0].len(), 3);
    }

    #[test]
    fn test_build_paths_empty() {
        let paths = build_paths(&[], 4);
        assert!(paths.is_empty());
    }

    #[test]
    fn test_build_paths_zero_groups() {
        let splits = vec![CpcvSplit {
            train_groups: vec![],
            test_groups: vec![0],
        }];
        let paths = build_paths(&splits, 0);
        assert!(paths.is_empty());
    }

    #[test]
    fn test_path_count_n4_k2() {
        // For N=4, k=2: C(4,2)=6 splits
        // Paths partition {0,1,2,3} into 2 disjoint pairs: 3 possible
        //   {0,1},{2,3}  {0,2},{1,3}  {0,3},{1,2}
        let config = CpcvConfig {
            n_groups: 4,
            n_test_groups: 2,
        };
        let splits = config.generate_splits();
        let paths = build_paths(&splits, 4);
        assert_eq!(
            paths.len(),
            3,
            "N=4,k=2 should have 3 paths, got {}",
            paths.len()
        );

        // Verify each path covers all groups exactly once
        for path in &paths {
            let mut covered = [false; 4];
            for &split_idx in path {
                for &g in &splits[split_idx].test_groups {
                    assert!(!covered[g]);
                    covered[g] = true;
                }
            }
            assert!(covered.iter().all(|&c| c));
        }
    }

    #[test]
    fn test_path_count_n6_k2() {
        // For N=6, k=2: ways to partition 6 items into 3 disjoint pairs = 15
        let config = CpcvConfig {
            n_groups: 6,
            n_test_groups: 2,
        };
        let splits = config.generate_splits();
        let paths = build_paths(&splits, 6);
        assert_eq!(
            paths.len(),
            15,
            "N=6,k=2 should have 15 paths, got {}",
            paths.len()
        );
    }
}
